<?php

namespace CS\ShopBundle\Repository;

/**
 * CrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrateRepository extends \Doctrine\ORM\EntityRepository
{
}
