<?php

namespace CS\ShopBundle\Repository;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
