<?php

namespace CS\ShopBundle\Repository;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends \Doctrine\ORM\EntityRepository
{
}
