<?php

namespace AppBundle\Repository;

/**
 * OrderCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCRepository extends \Doctrine\ORM\EntityRepository
{
}
