<?php

namespace AppBundle\Repository;

/**
 * UsersAdressesInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAdressesInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
