imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: CMS\UserBundle\Entity\User
#    service:
#        user_manager: cms_user.my_user_manager
#        mailer: fos_user.mailer.twig_swift
#    registration:
#        form:
#            type: cms_frontbundle_inscriptiontype
#        confirmation:
#            enabled:    true
#            template: CMSUserundle:Default:registration.email.twig
#            from_email:
#                address:        gilbert.armengaud@gmail.com
#                sender_name:    StartCMS Gilbert ARMENGAUD


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CS\ShopBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        contact.csgo@gmail.com
                sender_name:    CSGOFactory
            #template: templateEmail.html.twig

    resetting:
        email:
            from_email:
                address:        contact.csgo@gmail.com
                sender_name:    CSGOFactory


# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    port:       ~
    auth_mode:  login
    encryption: ssl


#    transport: '%mailer_transport%'
#    host:      '%mailer_host%'
#    username:  '%mailer_user%'
#    password:  '%mailer_password%'
#    encryption: ssl
#    #delivery_address: contact.csgo@gmail.com
#    #port: 465
#    auth_mode: login
#    spool:      { type: memory }

knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
              no-outline: true
              page-size: LETTER
              # Recommended to set UTF-8 as default encoding :)
              encoding: UTF-8
    image:
        enabled:    true
        #binary:  "wkhtmltopdf"
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []