admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

cs_shop:
    resource: "@CSShopBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
