services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    redirectionListener:
        class: CS\ShopBundle\Listener\RedirectionListener
        arguments: ["@service_container","@session"]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    shop_model.model_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CS\ShopBundle\Entity\Model

    shop.menu_builder:
        class: CS\ShopBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@shop_model.model_repository"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu