famillies:
    type:     rest
    resource: "@AppBundle/Controller/Rest/FamilliesController.php"

models:
    type:     rest
    resource: "@AppBundle/Controller/Rest/ModelsController.php"

crates:
    type:     rest
    resource: "@AppBundle/Controller/Rest/CratesController.php"

collections:
    type:     rest
    resource: "@AppBundle/Controller/Rest/CollectionsController.php"
