famillies:
    type:     rest
    resource: "@AppBundle/Controller/Rest/FamilliesController.php"

models:
    type:     rest
    resource: "@AppBundle/Controller/Rest/ModelsController.php"

weapons:
    type:     rest
    resource: "@AppBundle/Controller/Rest/WeaponsController.php"
